### ISSUE TITLE
`@cached()` seems to cache across component instances 

### ISSUE THREAD

**Issue by mydea** [ember-polyfills/ember-cached-decorator-polyfill#7]
Thanks for the work on this polyfill! I have been quite excited to try this out. However, it does not seem to work for me - the `@cached` value seems to be cached across all instances of a component.

A simple usage of this:

```js
import Component from '@glimmer/component';
import Ember from 'ember';
const cached = Ember._cached;

export default class LineChart extends Component {
  @cached
  get groupedData() {
    let { data } = this.args;

   console.log('groupedData is called');

   // transform the given data, and return it
   return data.map(() => /* ... */);
  }
}
```

However, multiple instances of the component all seem to share the same cached value. E.g. `groupedData is called` is only printed to the console once, even though there are multiple instances of the component rendered. I can also see this in tests, where in following tests the value is never recomputed, even though there are completely new component instances.

Maybe I am also doing something wrong? Not sure! Also not sure if this is related to this addon or to some underlying functionality here.. Is it working for you?

For reference, I am on ember-source 3.20.4.

**Comment by buschtoens** [comment]
Thanks for trying it out! Super glad that you have a use-case for it. 😍 

Most likely you are doing everything right and I messed up. Admittedly I did not get to try this polyfill myself yet. 😅 

I'll add a failing test case and fix. 👍

**Comment by buschtoens** [comment]
Fixed in [`v0.1.0-2`](https://github.com/ember-polyfills/ember-cached-decorator-polyfill/releases/tag/v0.1.0-2). Thank you! 🚀

**Comment by DLiblik** [comment]
I am still getting this issue in `v0.1.0-3`, but oddly, not for all properties.  The difference seems to be whether the cached property depends on any other properties on the same component instance - if not (i.e. if all tracked properties are on external objects), then the cache seems to have a different 'this' than properties that do depend on other properties on the same component instance and... weirdness and alternate dimensions start to appear with tentacles reaching out of my monitor.... then John Dies at the End.

Not sure I can put this into a simple repro easily... but this is very cool... huge performance gains for a few critical use cases.

**Comment by DLiblik** [comment]
Scratch that - I had an npm error I missed - was still running `v..-0` - `v..-3` does not have the problem.

Thanks for this polyfill - hugely useful.
